create table post_published_event_delivery
(
    id           bigint generated by default as identity primary key,
    event_id     uuid         not null,
    title        varchar(250) not null,
    slug         varchar(300) not null,
    content      text         not null,
    status       varchar(30)  not null,
    attempts     integer      not null default 0,
    last_error   text,
    dead_lettered_at timestamp,
    processed_at timestamp,
    constraint post_published_event_delivery_event_unique unique (event_id)
);
